# Generated by Django 4.1 on 2022-11-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_lyrics_content_alter_lyrics_song_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.BooleanField(null=True),
        ),
    ]
