# Generated by Django 4.1 on 2022-11-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_song_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artist_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='song_id',
        ),
    ]
